# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_ent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ad_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('video_url', models.CharField(max_length=500)),
            ],
        ),
    ]
