# Generated by Django 2.0.7 on 2018-07-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad_video',
            new_name='Ad_tv',
        ),
        migrations.RenameModel(
            old_name='Ad_ent',
            new_name='Ad_viral',
        ),
    ]
